### 

POST http://localhost:4004/user-management/syncusers
Authorization: Basic manage:
Content-Type: application/json

###

POST  http://localhost:3476/user-management/Users(email='emma.jones@hp.com',IsActiveEntity='true')/deactivateUserMain

